services:
  converter:
    build:
      context: converter
      dockerfile: Dockerfile
      target: converter-server
      platforms:
        - linux/amd64
    container_name: converter
    restart: unless-stopped
    volumes:
      - ./converter/config.toml:/app/config.toml:ro
    deploy:
      resources:
        limits:
          memory: 200MB
          cpus: 0.2
        reservations:
          cpus: 0.1
          memory: 20MB
