[package]
name = "statserver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "statserver"
path = "src/main.rs"

[dependencies]
futures = "0.3.31"
serde = { version = "1.0.217", features = ["derive"] }
surrealdb = "2.1.4"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
toml = "0.8.19"
